# Change these first
owner: Cap-go # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - riderx

sites:
  # - name: Capgo landing
  #   url: https://capgo.app
  # - name: Webapp
  #   url: https://web.capgo.app/
  # - name: API Load balancer
  #   url: https://api.capgo.app/ok
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"ok"}'
  # - name: API Cloudflare workers
  #   url: https://xvwzpoazmxkqosrdewyv.functions.supabase.co/ok
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"ok"}'
  # - name: API AWS
  #   url: https://web.capgo.app/ok
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"ok"}'
  # - name: API GCP
  #   url: https://web.capgo.app/ok
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"ok"}'
  # - name: Database Supabase
  #   url: https://xvwzpoazmxkqosrdewyv.supabase.co/functions/v1/ok?service=database
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"database"}'
  # - name: Database Netlify
  #   url: https://web.capgo.app/api/ok?service=database
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"database"}'
  # - name: Database Netlify Edge
  #   url: https://web.capgo.app/api/ok?service=database
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"database"}'
  # - name: Consistency between providers
  #   url: https://xvwzpoazmxkqosrdewyv.supabase.co/functions/v1/test_consistency
  #   __dangerous__body_down_if_text_missing: '{"status":"ok"}'
  # - name: Update endpoint Cloudflare (main)
  #   url: https://xvwzpoazmxkqosrdewyv.supabase.co/functions/v1/ok?service=update
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"update"}'
  # - name: Update endpoint GCP (backup 1)
  #   url: https://web.capgo.app/api-edge/ok?service=update
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"update"}'
  # - name: Update endpoint AWS (backup 2)
  #   url: https://web.capgo.app/api/ok?service=update
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"update"}'
  # - name: Stats endpoint Cloudflare (main)
  #   url: https://xvwzpoazmxkqosrdewyv.supabase.co/functions/v1/ok?service=stats
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"stats"}'
  # - name: Stats endpoint GCP (backup 1)
  #   url: https://web.capgo.app/api-edge/ok?service=stats
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"stats"}'
  # - name: Stats endpoint AWS (backup 2)
  #   url: https://web.capgo.app/api/ok?service=stats
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"stats"}'
  # - name: Plugin Get channels endpoint AWS
  #   url: https://web.capgo.app/api/ok?service=channel_self_get
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"channel_self_get"}'
  # - name: Plugin Get channels endpoint GCP
  #   url: https://web.capgo.app/api-edge/ok?service=channel_self_get
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"channel_self_get"}'
  # - name: Plugin Get channels endpoint Cloudflare
  #   url: https://xvwzpoazmxkqosrdewyv.supabase.co/functions/v1/ok?service=channel_self_get
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"channel_self_get"}'
  # - name: API Get devices endpoint AWS
  #   url: https://web.capgo.app/api/ok?service=device_get
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"device_get"}'
  # - name: API Get devices endpoint GCP
  #   url: https://web.capgo.app/api-edge/ok?service=device_get
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"device_get"}'
  # - name: API Get devices endpoint Cloudflare
  #   url: https://xvwzpoazmxkqosrdewyv.supabase.co/functions/v1/ok?service=device_get
  #   __dangerous__body_down_if_text_missing: '{"status":"ok","service":"device_get"}'
status-website:
  favicon: https://raw.githubusercontent.com/Cap-go/capgo/main/assets/logo.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.capgo.app
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Cap-go/website/main/public/capgo.webp
  name: Capgo status
  introTitle: "This status page automatically monitors our systems and alerts if something is not working as expected."
  introMessage: This is a status page which uses just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Website
      href: https://capgo.app
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
