# Change these first
owner: Cap-go # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Capgo landing
    url: https://capgo.app
  - name: Webapp
    url: https://web.capgo.app/
  - name: API Load balancer
    url: https://api.capgo.app/ok
  - name: API Cloudflare workers
    url: https://xvwzpoazmxkqosrdewyv.functions.supabase.co/ok
  - name: API AWS
    url: https://web.capgo.app/ok
  - name: API GCP
    url: https://web.capgo.app/ok
  - name: Database Supabase
    url: https://supabase.capgo.app/ok?service=database
  - name: Database Netlify
    url: https://netlify.capgo.app/ok?service=database
  - name: Database Netlify Edge
    url: https://netlify-edge.capgo.app/ok?service=database

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.capgo.app
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Cap-go/website/main/public/capgo_logo.webp
  name: Capgo Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
